#!/usr/bin/env bash
# Build dist/ — the contents of the root domain's document root.
#
# Same content-hash-on-CSS trick as unhack-fl/build.sh, so a style change
# doesn't need a manual cache purge.
#
#   ./build.sh            build dist/
#   ./build.sh --deploy   build, then rsync to the server over SSH
#
# IMPORTANT: the target directory also holds fl/ (the Florida subdomain's
# own docroot, a sibling here rather than a separate vhost). rsync below
# deliberately has no --delete, so it can only add/update the files this
# script actually produces — it must never be given one, or a deploy from
# here would wipe out fl/.
set -euo pipefail
cd "$(dirname "$0")"

REMOTE_HOST="hostinger"
REMOTE_DIR="domains/unhackdemocracy.us/public_html"

# Every page carries a byte-identical header, generated by tools/navgen.py.
# Checked here rather than merely documented, because the failure mode is
# silent: a nav updated on five pages out of six looks completely fine
# until somebody lands on the sixth and finds no way onward. Fail fast,
# before anything is built or uploaded.
python3 tools/navgen.py --check

rm -rf dist unhack-root-deploy.zip
mkdir -p dist

cp web/logo.svg web/social-preview.jpg web/social-preview-hero.jpg dist/
cp web/civics-data.js web/civics-quiz.js web/civics-exam.js dist/
cp web/.htaccess dist/.htaccess

hash_of() { shasum -a 256 "$1" | cut -c1-8; }

# The civics quiz's two scripts get the same content hash treatment as the
# stylesheet, and for the same reason: a stale cached quiz that scores
# answers against last week's data is worse than a broken one, because it
# looks like it is working. Both files share one hash — they always ship
# together, so busting them together costs nothing.
JS_HASH=$(hash_of web/civics-data.js)$(hash_of web/civics-quiz.js)$(hash_of web/civics-exam.js)
CSS_HASH=$(hash_of web/styles.css)
for page in index about states resources citizen-primer citizenship-test; do
  sed -e "s|href=\"styles\.css\"|href=\"styles.css?v=${CSS_HASH}\"|" \
      -e "s|src=\"civics-\([a-z]*\)\.js\"|src=\"civics-\1.js?v=${JS_HASH}\"|g" \
    "web/${page}.html" > "dist/${page}.html"
  grep -q "styles.css?v=${CSS_HASH}" "dist/${page}.html" || { echo "FAIL: css not stamped in ${page}.html"; exit 1; }
done
cp web/styles.css "dist/styles.css"

( cd dist && zip -qr ../unhack-root-deploy.zip . -x ".DS_Store" )

echo "built dist/  css=${CSS_HASH}"

# Is what we are about to publish reproducible from what is published?
#
# `--deploy` rsyncs to the web host. It has nothing to do with git, and its
# verification proves the SITE is current while saying nothing about the
# repo behind it. Those came apart for a whole day: seventeen commits sat
# unpushed while every deploy reported HTTP 200, and the repo went public
# in the middle of it — so anyone following the footer link found a project
# missing the thing the site is about.
#
# A passing check tells you only about what it measures. This measures the
# other half.
#
# It warns rather than blocks. Building and deploying from a dirty tree is
# normal while iterating, and a deploy script that refuses to run is a
# deploy script people work around.
check_repo_matches() {
  git rev-parse --is-inside-work-tree >/dev/null 2>&1 || return 0

  local dirty ahead upstream
  dirty=$(git status --porcelain 2>/dev/null | wc -l | tr -d ' ')
  upstream=$(git rev-parse --abbrev-ref '@{u}' 2>/dev/null || true)
  ahead=0
  [[ -n "$upstream" ]] && ahead=$(git rev-list --count '@{u}..HEAD' 2>/dev/null || echo 0)

  [[ "$dirty" == 0 && "$ahead" == 0 && -n "$upstream" ]] && return 0

  echo
  echo "  ⚠  what you are deploying is not fully published:"
  [[ "$dirty" != 0 ]] && echo "       ${dirty} uncommitted change(s) in the working tree"
  [[ "$ahead" != 0 ]] && echo "       ${ahead} commit(s) not pushed to ${upstream}"
  [[ -z "$upstream" ]] && echo "       this branch has no upstream, so nothing is published at all"
  echo "     The live site will not be reproducible from the repo."
  [[ "$ahead" != 0 ]] && echo "     Fix: git push"
  echo
}

if [[ "${1:-}" == "--deploy" ]]; then
  check_repo_matches
  echo "deploying to ${REMOTE_HOST}:~/${REMOTE_DIR}/ (fl/ untouched — no --delete)"
  rsync -az --no-perms --omit-dir-times \
    -e "ssh -o BatchMode=yes" dist/ "${REMOTE_HOST}:~/${REMOTE_DIR}/"
  echo "deployed. verifying what's served:"
  sleep 2
  curl -s --max-time 20 "https://unhackdemocracy.us/styles.css?v=${CSS_HASH}" \
    | grep -c "unhackdemocracy.us on purpose" | sed 's/^/  styles.css served correctly: /'
  echo "  homepage title: $(curl -s --max-time 20 https://unhackdemocracy.us | grep -o '<title>[^<]*' | head -1)"
  check_repo_matches
fi
