#!/usr/bin/env python3
"""Generate web/shelf-data.js from data/shelf.json.

    python3 tools/shelfgen.py           rewrite web/shelf-data.js
    python3 tools/shelfgen.py --check   fail if it is out of date

Same contract as navgen.py, and for the same reason. The shelf is a
catalogue of somebody else's documents: titles change, URLs rot, guides
get added and withdrawn. Hand-maintaining a JavaScript literal is how a
link quietly starts 404-ing and nobody notices, because the page still
renders perfectly and just sends people nowhere.

So data/shelf.json is the source of truth, this generates the shipped
file, and --check runs in build.sh so an edit to the wrong file fails the
build instead of reaching the server.

WHAT THIS CHECK DOES NOT DO: touch the network. Whether a URL still
resolves is tools/shelf_verify.py's job, run deliberately, because a
build that makes HTTP calls fails on a bad hotel wifi and teaches people
to work around it.
"""

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DB = ROOT / "data" / "shelf.json"
OUT = ROOT / "web" / "shelf-data.js"

REQUIRED = ("id", "source", "action", "blurb", "title", "where", "url",
            "button", "mode", "capacity", "reach", "disposition", "verified")
MODES = {"understand", "do", "both"}
CAPS = {"minutes", "hour", "day", "many"}
REACH = {"group", "solo", "either"}
DISPOSITIONS = {"make", "talk", "dig", "showup", "support", "learn"}


def validate(db):
    """Everything checkable without a network, checked before it ships."""
    problems = []
    seen = set()
    for it in db["items"]:
        where = it.get("id", "<no id>")
        for f in REQUIRED:
            if not it.get(f):
                problems.append(f"{where}: missing {f}")
        if it.get("id") in seen:
            problems.append(f"{where}: duplicate id")
        seen.add(it.get("id"))
        if it.get("source") not in db["sources"]:
            problems.append(f"{where}: unknown source {it.get('source')!r}")
        if it.get("mode") not in MODES:
            problems.append(f"{where}: mode {it.get('mode')!r}")
        if it.get("capacity") not in CAPS:
            problems.append(f"{where}: capacity {it.get('capacity')!r}")
        if it.get("reach") not in REACH:
            problems.append(f"{where}: reach {it.get('reach')!r}")
        bad = set(it.get("disposition") or []) - DISPOSITIONS
        if bad:
            problems.append(f"{where}: disposition {sorted(bad)}")
        if not it.get("disposition"):
            problems.append(f"{where}: no disposition, so nothing can match it")
        # An outline that nobody read is a fabricated outline waiting to
        # happen. The two fields have to agree.
        if it.get("outline") and not it.get("outline_read"):
            problems.append(f"{where}: has an outline with no outline_read date")
        if it.get("outline_read") and not it.get("outline"):
            problems.append(f"{where}: outline_read set but no outline")
    return problems


def render(db):
    items = []
    for it in db["items"]:
        items.append({k: it[k] for k in (
            "id", "action", "blurb", "title", "where", "url", "button",
            "mode", "capacity", "reach", "disposition") if k in it})
        items[-1]["outline"] = it.get("outline")
    src = db["sources"]["opet"]
    body = json.dumps(items, indent=2, ensure_ascii=False)
    return f"""/* GENERATED by tools/shelfgen.py from data/shelf.json — do not edit.
 *
 * The shelf: capability resources, sorted out of the pantry by one test —
 * does this teach a capability the reader keeps, or recruit for a
 * position? What was excluded, and why, is recorded in data/shelf.json
 * rather than lost, so the sorting stays auditable.
 *
 * `outline` is null wherever nobody has read the guide yet. It is never
 * inferred from a title: inventing the contents of somebody else's
 * document is exactly what the primary-source rule forbids, and a
 * plausible outline is worse than none because nobody checks it.
 *
 * Nothing here is hosted. These are their documents and we link to them.
 */

const SHELF_SOURCE = {{
  name: {json.dumps(src["name"], ensure_ascii=False)},
  href: {json.dumps(src["index"], ensure_ascii=False)},
}};

const SHELF = {body};
"""


def main():
    db = json.loads(DB.read_text())
    problems = validate(db)
    if problems:
        print("FAIL: data/shelf.json")
        for p in problems:
            print("   ", p)
        raise SystemExit(1)

    want = render(db)
    check = "--check" in sys.argv[1:]
    have = OUT.read_text() if OUT.exists() else ""
    if check:
        if have != want:
            raise SystemExit(
                "FAIL: web/shelf-data.js is out of date.\n"
                "      Edit data/shelf.json, then run: python3 tools/shelfgen.py")
        print(f"shelf: up to date ({len(db['items'])} items, "
              f"{sum(1 for i in db['items'] if i.get('outline'))} with outlines)")
        return
    OUT.write_text(want)
    print(f"wrote web/shelf-data.js ({len(db['items'])} items)")


if __name__ == "__main__":
    main()
