// The 2025 naturalization civics test — all 128 questions, from USCIS.
//
// Source: "Civics Questions and Answers for the Naturalization Test
// (2025 version)", uscis.gov/citizenship. Published by USCIS, a work of
// the U.S. government. Extracted from the PDF and checked against the
// rendered pages, not retyped.
//
// WHICH TEST THIS IS. There are two in force. Form N-400 filed BEFORE
// 20 October 2025 means the 2008 test: 100 questions, 10 asked, 6 to
// pass. Filed ON OR AFTER means this one: 128 questions, 20 asked, 12 to
// pass. This file is only the 2025 set, and the page asks before it
// quizzes — practising the wrong bank before a real interview is worse
// than not practising.
//
// `kind` is the important field:
//   static — the answer does not change. 120 of the 128.
//   lookup — the answer changes with elections, appointments, or where
//            you live, so NO answer is stored. Shipping a fixed answer
//            for "who is the President now" means confidently teaching
//            the wrong one the day after an election. These link to the
//            USCIS updates page instead of being scored.
//
// `answers` is a SET, and any member is correct — which is how the real
// interview works, where the officer accepts any valid answer. 80 of the
// 128 have more than one; question 117 has twenty-five.
//
// `need` is how many items the question actually asks for. Most want one,
// but seven want two, three or five — "Name two promises...", "Name five
// of the original states". Treating those as one-and-done marked them
// correct after a single pick, which is not what the interview asks.
//
// `cat` is what KIND of thing the answer is, taken from the question stem
// because the stem states it outright. It exists to pick distractors: a
// war is offered against other wars, so answering needs actual knowledge
// rather than noticing that four options are not wars. Derived FORM-FIRST
// — "Why did the US enter the Korean War" is about a war but its answer is
// a reason, and getting that backwards offered Vietnam as a distractor for
// a question about motives.
//
// `star` marks the 20 questions an applicant 65 or older who has been a
// permanent resident 20+ years may study instead of all 128.

const CIVICS_VERSION = "2025";
const CIVICS_SOURCE = "https://www.uscis.gov/citizenship/2025test";
const CIVICS_UPDATES = "https://www.uscis.gov/citizenship/testupdates";

const CIVICS = [
  { n: 1, sub: "Principles of American Government", cat: "system",
    q: "What is the form of government of the United States?",
    a: ["Republic", "Constitution-based federal republic", "Representative democracy"], r: true },
  { n: 2, sub: "Principles of American Government", cat: "named",
    q: "What is the supreme law of the land?",
    a: ["(U.S.) Constitution"], r: true, star: true },
  { n: 3, sub: "Principles of American Government", cat: "general",
    q: "Name one thing the U.S. Constitution does.",
    a: ["Forms the government", "Defines powers of government", "Defines the parts of government", "Protects the rights of the people"] },
  { n: 4, sub: "Principles of American Government", cat: "meaning",
    q: "The U.S. Constitution starts with the words “We the People.” What does “We the People” mean?",
    a: ["Self-government", "Popular sovereignty", "Consent of the governed", "People should govern themselves", "(Example of) social contract"] },
  { n: 5, sub: "Principles of American Government", cat: "process",
    q: "How are changes made to the U.S. Constitution?",
    a: ["Amendments", "The amendment process"], r: true },
  { n: 6, sub: "Principles of American Government", cat: "right",
    q: "What does the Bill of Rights protect?",
    a: ["(The basic) rights of Americans", "(The basic) rights of people living in the United States"] },
  { n: 7, sub: "Principles of American Government", cat: "count",
    q: "How many amendments does the U.S. Constitution have?",
    a: ["Twenty-seven (27)"], star: true },
  { n: 8, sub: "Principles of American Government", cat: "reason",
    q: "Why is the Declaration of Independence important?",
    a: ["It says America is free from British control.", "It says all people are created equal.", "It identifies inherent rights.", "It identifies individual freedoms."] },
  { n: 9, sub: "Principles of American Government", cat: "document",
    q: "What founding document said the American colonies were free from Britain?",
    a: ["Declaration of Independence"] },
  { n: 10, sub: "Principles of American Government", cat: "general", need: 2,
    q: "Name two important ideas from the Declaration of Independence and the U.S. Constitution.",
    a: ["Equality", "Liberty", "Social contract", "Natural rights", "Limited government", "Self-government"] },
  { n: 11, sub: "Principles of American Government", cat: "document",
    q: "The words “Life, Liberty, and the pursuit of Happiness” are in what founding document?",
    a: ["Declaration of Independence"] },
  { n: 12, sub: "Principles of American Government", cat: "system",
    q: "What is the economic system of the United States?",
    a: ["Capitalism", "Free market economy"], r: true, star: true },
  { n: 13, sub: "Principles of American Government", cat: "meaning",
    q: "What is the rule of law?",
    a: ["Everyone must follow the law.", "Leaders must obey the law.", "Government must obey the law.", "No one is above the law."] },
  { n: 14, sub: "Principles of American Government", cat: "document",
    q: "Many documents influenced the U.S. Constitution. Name one.",
    a: ["Declaration of Independence", "Articles of Confederation", "Federalist Papers", "Anti-Federalist Papers", "Virginia Declaration of Rights", "Fundamental Orders of Connecticut", "Mayflower Compact", "Iroquois Great Law of Peace"], r: true },
  { n: 15, sub: "Principles of American Government", cat: "reason",
    q: "There are three branches of government. Why?",
    a: ["So one part does not become too powerful", "Checks and balances", "Separation of powers"] },
  { n: 16, sub: "System of Government", cat: "branch",
    q: "Name the three branches of government.",
    a: ["Legislative, executive, and judicial", "Congress, president, and the courts"] },
  { n: 17, sub: "System of Government", cat: "branch",
    q: "The President of the United States is in charge of which branch of government?",
    a: ["Executive branch"], d: ["Legislative", "Judicial"] },
  { n: 18, sub: "System of Government", cat: "power",
    q: "What part of the federal government writes laws?",
    a: ["(U.S.) Congress", "(U.S. or national) legislature", "Legislative branch"], d: ["The executive branch", "The judicial branch"] },
  { n: 19, sub: "System of Government", cat: "branch",
    q: "What are the two parts of the U.S. Congress?",
    a: ["Senate and House (of Representatives)"] },
  { n: 20, sub: "System of Government", cat: "power",
    q: "Name one power of the U.S. Congress.",
    a: ["Writes laws", "Declares war", "Makes the federal budget"], star: true },
  { n: 21, sub: "System of Government", cat: "count",
    q: "How many U.S. senators are there?",
    a: ["One hundred (100)"] },
  { n: 22, sub: "System of Government", cat: "duration",
    q: "How long is a term for a U.S. senator?",
    a: ["Six (6) years"] },
  { n: 23, sub: "System of Government", cat: "who",
    q: "Who is one of your state’s U.S. senators now?",
    a: [], kind: "lookup" },
  { n: 24, sub: "System of Government", cat: "count",
    q: "How many voting members are in the House of Representatives?",
    a: ["Four hundred thirty-five (435)"] },
  { n: 25, sub: "System of Government", cat: "duration",
    q: "How long is a term for a member of the House of Representatives?",
    a: ["Two (2) years"] },
  { n: 26, sub: "System of Government", cat: "reason",
    q: "Why do U.S. representatives serve shorter terms than U.S. senators?",
    a: ["To more closely follow public opinion"] },
  { n: 27, sub: "System of Government", cat: "count",
    q: "How many senators does each state have?",
    a: ["Two (2)"] },
  { n: 28, sub: "System of Government", cat: "reason",
    q: "Why does each state have two senators?",
    a: ["Equal representation (for small states)", "The Great Compromise (Connecticut Compromise)"] },
  { n: 29, sub: "System of Government", cat: "general",
    q: "Name your U.S. representative.",
    a: [], kind: "lookup" },
  { n: 30, sub: "System of Government", cat: "named",
    q: "What is the name of the Speaker of the House of Representatives now?",
    a: [], star: true, kind: "lookup" },
  { n: 31, sub: "System of Government", cat: "who",
    q: "Who does a U.S. senator represent?",
    a: ["Citizens of their state", "People of their state"] },
  { n: 32, sub: "System of Government", cat: "who",
    q: "Who elects U.S. senators?",
    a: ["Citizens from their state"] },
  { n: 33, sub: "System of Government", cat: "who",
    q: "Who does a member of the House of Representatives represent?",
    a: ["Citizens in their (congressional) district", "Citizens in their district", "People from their (congressional) district", "People in their district"] },
  { n: 34, sub: "System of Government", cat: "who",
    q: "Who elects members of the House of Representatives?",
    a: ["Citizens from their (congressional) district"] },
  { n: 35, sub: "System of Government", cat: "reason",
    q: "Some states have more representatives than other states. Why?",
    a: ["(Because of) the state’s population", "(Because) they have more people", "(Because) some states have more people"] },
  { n: 36, sub: "System of Government", cat: "duration",
    q: "The President of the United States is elected for how many years?",
    a: ["Four (4) years"], star: true },
  { n: 37, sub: "System of Government", cat: "reason",
    q: "The President of the United States can serve only two terms. Why?",
    a: ["(Because of) the 22nd Amendment", "To keep the president from becoming too powerful"] },
  { n: 38, sub: "System of Government", cat: "named",
    q: "What is the name of the President of the United States now?",
    a: [], star: true, kind: "lookup" },
  { n: 39, sub: "System of Government", cat: "named",
    q: "What is the name of the Vice President of the United States now?",
    a: [], star: true, kind: "lookup" },
  { n: 40, sub: "System of Government", cat: "who",
    q: "If the president can no longer serve, who becomes president?",
    a: ["The Vice President (of the United States)"] },
  { n: 41, sub: "System of Government", cat: "power",
    q: "Name one power of the president.",
    a: ["Signs bills into law", "Vetoes bills", "Enforces laws", "Commander in Chief (of the military)", "Chief diplomat", "Appoints federal judges"] },
  { n: 42, sub: "System of Government", cat: "who",
    q: "Who is Commander in Chief of the U.S. military?",
    a: ["The President (of the United States)"] },
  { n: 43, sub: "System of Government", cat: "who",
    q: "Who signs bills to become laws?",
    a: ["The President (of the United States)"] },
  { n: 44, sub: "System of Government", cat: "who",
    q: "Who vetoes bills?",
    a: ["The President (of the United States)"], star: true },
  { n: 45, sub: "System of Government", cat: "who",
    q: "Who appoints federal judges?",
    a: ["The President (of the United States)"] },
  { n: 46, sub: "System of Government", cat: "branch",
    q: "The executive branch has many parts. Name one.",
    a: ["President (of the United States)", "Cabinet", "Federal departments and agencies"] },
  { n: 47, sub: "System of Government", cat: "cabinet",
    q: "What does the President’s Cabinet do?",
    a: ["Advises the President (of the United States)"], r: true },
  { n: 48, sub: "System of Government", cat: "posts", need: 2,
    q: "What are two Cabinet-level positions?",
    a: ["Attorney General", "Secretary of Agriculture", "Secretary of Commerce", "Secretary of Education", "Secretary of Energy", "Secretary of Health and Human Services", "Secretary of Homeland Security", "Secretary of Housing and Urban Development", "Secretary of the Interior", "Secretary of Labor", "Secretary of State", "Secretary of Transportation", "Secretary of the Treasury", "Secretary of Veterans Affairs", "Secretary of War (Defense)", "Vice-President", "Administrator of the Environmental Protection Agency", "Administrator of the Small Business Administration", "Director of the Central Intelligence Agency", "Director of the Office of Management and Budget", "Director of National Intelligence", "United States Trade Representative"], r: true },
  { n: 49, sub: "System of Government", cat: "reason",
    q: "Why is the Electoral College important?",
    a: ["It decides who is elected president.", "It provides a compromise between the popular election of the president and congressional selection."] },
  { n: 50, sub: "System of Government", cat: "posts",
    q: "What is one part of the judicial branch?",
    a: ["Supreme Court", "Federal Courts"] },
  { n: 51, sub: "System of Government", cat: "power",
    q: "What does the judicial branch do?",
    a: ["Reviews laws", "Explains laws", "Resolves disputes (disagreements) about the law", "Decides if a law goes against the (U.S.) Constitution"] },
  { n: 52, sub: "System of Government", cat: "posts",
    q: "What is the highest court in the United States?",
    a: ["Supreme Court"], star: true },
  { n: 53, sub: "System of Government", cat: "count",
    q: "How many seats are on the Supreme Court?",
    a: ["Nine (9)"] },
  { n: 54, sub: "System of Government", cat: "count",
    q: "How many Supreme Court justices are usually needed to decide a case?",
    a: ["Five (5)"] },
  { n: 55, sub: "System of Government", cat: "duration",
    q: "How long do Supreme Court justices serve?",
    a: ["(For) life", "Lifetime appointment", "(Until) retirement"], r: true },
  { n: 56, sub: "System of Government", cat: "reason",
    q: "Supreme Court justices serve for life. Why?",
    a: ["To be independent (of politics)", "To limit outside (political) influence"] },
  { n: 57, sub: "System of Government", cat: "who",
    q: "Who is the Chief Justice of the United States now?",
    a: [], kind: "lookup" },
  { n: 58, sub: "System of Government", cat: "power",
    q: "Name one power that is only for the federal government.",
    a: ["Print paper money", "Mint coins", "Declare war", "Create an army", "Make treaties", "Set foreign policy"] },
  { n: 59, sub: "System of Government", cat: "power",
    q: "Name one power that is only for the states.",
    a: ["Provide schooling and education", "Provide protection (police)", "Provide safety (fire departments)", "Give a driver’s license", "Approve zoning and land use"] },
  { n: 60, sub: "System of Government", cat: "amendment",
    q: "What is the purpose of the 10th Amendment?",
    a: ["(It states that the) powers not given to the federal government belong to the states or to the people."] },
  { n: 61, sub: "System of Government", cat: "who",
    q: "Who is the governor of your state now?",
    a: [], star: true, kind: "lookup" },
  { n: 62, sub: "System of Government", cat: "place",
    q: "What is the capital of your state?",
    a: [], kind: "lookup" },
  { n: 63, sub: "Rights and Responsibilities", cat: "amendment",
    q: "There are four amendments to the U.S. Constitution about who can vote. Describe one of them.",
    a: ["Citizens eighteen (18) and older (can vote).", "You don’t have to pay (a poll tax) to vote.", "Any citizen can vote. (Women and men can vote.)", "A male citizen of any race (can vote)."], r: true },
  { n: 64, sub: "Rights and Responsibilities", cat: "who",
    q: "Who can vote in federal elections, run for federal office, and serve on a jury in the United States?",
    a: ["Citizens", "Citizens of the United States", "U.S. citizens"] },
  { n: 65, sub: "Rights and Responsibilities", cat: "right", need: 3,
    q: "What are three rights of everyone living in the United States?",
    a: ["Freedom of expression", "Freedom of speech", "Freedom of assembly", "Freedom to petition the government", "Freedom of religion", "The right to bear arms"], r: true },
  { n: 66, sub: "Rights and Responsibilities", cat: "named",
    q: "What do we show loyalty to when we say the Pledge of Allegiance?",
    a: ["The United States", "The flag"], d: ["(U.S.) Constitution", "The President (of the United States)", "(U.S.) Congress", "The Star-Spangled Banner"], star: true },
  { n: 67, sub: "Rights and Responsibilities", cat: "duty", need: 2,
    q: "Name two promises that new citizens make in the Oath of Allegiance.",
    a: ["Give up loyalty to other countries", "Defend the (U.S.) Constitution", "Obey the laws of the United States", "Serve in the military (if needed)", "Serve (help, do important work for) the nation (if needed)", "Be loyal to the United States"] },
  { n: 68, sub: "Rights and Responsibilities", cat: "process",
    q: "How can people become United States citizens?",
    a: ["Be born in the United States, under the conditions set by the 14th Amendment", "Naturalize", "Derive citizenship (under conditions set by Congress)"], r: true },
  { n: 69, sub: "Rights and Responsibilities", cat: "duty", need: 2,
    q: "What are two examples of civic participation in the United States?",
    a: ["Vote", "Run for office", "Join a political party", "Help with a campaign", "Join a civic group", "Join a community group", "Give an elected official your opinion (on an issue)", "Contact elected officials", "Support or oppose an issue or policy", "Write to a newspaper"] },
  { n: 70, sub: "Rights and Responsibilities", cat: "duty",
    q: "What is one way Americans can serve their country?",
    a: ["Vote", "Pay taxes", "Obey the law", "Serve in the military", "Run for office", "Work for local, state, or federal government"] },
  { n: 71, sub: "Rights and Responsibilities", cat: "reason",
    q: "Why is it important to pay federal taxes?",
    a: ["Required by law", "All people pay to fund the federal government", "Required by the (U.S.) Constitution (16th Amendment)", "Civic duty"] },
  { n: 72, sub: "Rights and Responsibilities", cat: "reason",
    q: "It is important for all men age 18 through 25 to register for the Selective Service. Name one reason why.",
    a: ["Required by law", "Civic duty", "Makes the draft fair, if needed"] },
  { n: 73, sub: "Colonial Period and Independence", cat: "reason",
    q: "The colonists came to America for many reasons. Name one.",
    a: ["Freedom", "Political liberty", "Religious freedom", "Economic opportunity", "Escape persecution"] },
  { n: 74, sub: "Colonial Period and Independence", cat: "who",
    q: "Who lived in America before the Europeans arrived?",
    a: ["American Indians", "Native Americans"], star: true },
  { n: 75, sub: "Colonial Period and Independence", cat: "group",
    q: "What group of people was taken and sold as slaves?",
    a: ["Africans", "People from Africa"], r: true },
  { n: 76, sub: "Colonial Period and Independence", cat: "war",
    q: "What war did the Americans fight to win independence from Britain?",
    a: ["American Revolution", "The (American) Revolutionary War", "War for (American) Independence"] },
  { n: 77, sub: "Colonial Period and Independence", cat: "reason",
    q: "Name one reason why the Americans declared independence from Britain.",
    a: ["High taxes", "Taxation without representation", "British soldiers stayed in Americans’ houses (boarding, quartering)", "They did not have self-government", "Boston Massacre", "Boston Tea Party (Tea Act)", "Stamp Act", "Sugar Act", "Townshend Acts", "Intolerable (Coercive) Acts"] },
  { n: 78, sub: "Colonial Period and Independence", cat: "person",
    q: "Who wrote the Declaration of Independence?",
    a: ["(Thomas) Jefferson"], star: true },
  { n: 79, sub: "Colonial Period and Independence", cat: "when",
    q: "When was the Declaration of Independence adopted?",
    a: ["July 4, 1776"] },
  { n: 80, sub: "Colonial Period and Independence", cat: "event",
    q: "The American Revolution had many important events. Name one.",
    a: ["(Battle of) Bunker Hill", "Declaration of Independence", "Washington Crossing the Delaware (Battle of Trenton)", "(Battle of) Saratoga", "Valley Forge (Encampment)", "(Battle of) Yorktown (British surrender at Yorktown)"] },
  { n: 81, sub: "Colonial Period and Independence", cat: "state", need: 5,
    q: "There were 13 original states. Name five.",
    a: ["New Hampshire", "Massachusetts", "Rhode Island", "Connecticut", "New York", "New Jersey", "Pennsylvania", "Delaware", "Maryland", "Virginia", "North Carolina", "South Carolina", "Georgia"], r: true },
  { n: 82, sub: "Colonial Period and Independence", cat: "document",
    q: "What founding document was written in 1787?",
    a: ["(U.S.) Constitution"] },
  { n: 83, sub: "Colonial Period and Independence", cat: "person",
    q: "The Federalist Papers supported the passage of the U.S. Constitution. Name one of the writers.",
    a: ["(James) Madison", "(Alexander) Hamilton", "(John) Jay", "Publius"] },
  { n: 84, sub: "Colonial Period and Independence", cat: "reason",
    q: "Why were the Federalist Papers important?",
    a: ["They helped people understand the (U.S.) Constitution.", "They supported passing the (U.S.) Constitution."] },
  { n: 85, sub: "Colonial Period and Independence", cat: "famous",
    q: "Benjamin Franklin is famous for many things. Name one.",
    a: ["Founded the first free public libraries", "First Postmaster General of the United States", "Helped write the Declaration of Independence", "Inventor", "U.S. diplomat"] },
  { n: 86, sub: "Colonial Period and Independence", cat: "famous",
    q: "George Washington is famous for many things. Name one.",
    a: ["“Father of Our Country”", "First president of the United States", "General of the Continental Army", "President of the Constitutional Convention"], star: true },
  { n: 87, sub: "Colonial Period and Independence", cat: "famous",
    q: "Thomas Jefferson is famous for many things. Name one.",
    a: ["Writer of the Declaration of Independence", "Third president of the United States", "Doubled the size of the United States (Louisiana Purchase)", "First Secretary of State", "Founded the University of Virginia", "Writer of the Virginia Statute on Religious Freedom"] },
  { n: 88, sub: "Colonial Period and Independence", cat: "famous",
    q: "James Madison is famous for many things. Name one.",
    a: ["“Father of the Constitution”", "Fourth president of the United States", "President during the War of 1812", "One of the writers of the Federalist Papers"] },
  { n: 89, sub: "Colonial Period and Independence", cat: "famous",
    q: "Alexander Hamilton is famous for many things. Name one.",
    a: ["First Secretary of the Treasury", "One of the writers of the Federalist Papers", "Helped establish the First Bank of the United States", "Aide to General George Washington", "Member of the Continental Congress"] },
  { n: 90, sub: "1800s", cat: "place",
    q: "What territory did the United States buy from France in 1803?",
    a: ["Louisiana Territory", "Louisiana"], r: true },
  { n: 91, sub: "1800s", cat: "war",
    q: "Name one war fought by the United States in the 1800s.",
    a: ["War of 1812", "Mexican-American War", "Civil War", "Spanish-American War"] },
  { n: 92, sub: "1800s", cat: "war",
    q: "Name the U.S. war between the North and the South.",
    a: ["The Civil War"] },
  { n: 93, sub: "1800s", cat: "event",
    q: "The Civil War had many important events. Name one.",
    a: ["(Battle of) Fort Sumter", "Emancipation Proclamation", "(Battle of) Vicksburg", "(Battle of) Gettysburg", "Sherman’s March", "(Surrender at) Appomattox", "(Battle of) Antietam/Sharpsburg", "Lincoln was assassinated."] },
  { n: 94, sub: "1800s", cat: "famous",
    q: "Abraham Lincoln is famous for many things. Name one.",
    a: ["Freed the slaves (Emancipation Proclamation)", "Saved (or preserved) the Union", "Led the United States during the Civil War", "16th president of the United States", "Delivered the Gettysburg Address"], star: true },
  { n: 95, sub: "1800s", cat: "describes",
    q: "What did the Emancipation Proclamation do?",
    a: ["Freed the slaves", "Freed slaves in the Confederacy", "Freed slaves in the Confederate states", "Freed slaves in most Southern states"] },
  { n: 96, sub: "1800s", cat: "war",
    q: "What U.S. war ended slavery?",
    a: ["The Civil War"] },
  { n: 97, sub: "1800s", cat: "amendname",
    q: "What amendment says all persons born or naturalized in the United States, and subject to the jurisdiction thereof, are U.S. citizens?",
    a: ["14th Amendment"], r: true },
  { n: 98, sub: "1800s", cat: "when",
    q: "When did all men get the right to vote?",
    a: ["After the Civil War", "During Reconstruction", "(With the) 15th Amendment", "1870"] },
  { n: 99, sub: "1800s", cat: "person",
    q: "Name one leader of the women’s rights movement in the 1800s.",
    a: ["Susan B. Anthony", "Elizabeth Cady Stanton", "Sojourner Truth", "Harriet Tubman", "Lucretia Mott", "Lucy Stone"], r: true },
  { n: 100, sub: "Recent American History and Other Important Historical Information", cat: "war",
    q: "Name one war fought by the United States in the 1900s.",
    a: ["World War I", "World War II", "Korean War", "Vietnam War", "(Persian) Gulf War"] },
  { n: 101, sub: "Recent American History and Other Important Historical Information", cat: "reason",
    q: "Why did the United States enter World War I?",
    a: ["Because Germany attacked U.S. (civilian) ships", "To support the Allied Powers (England, France, Italy, and Russia)", "To oppose the Central Powers (Germany, Austria-Hungary, the Ottoman Empire, and Bulgaria)"] },
  { n: 102, sub: "Recent American History and Other Important Historical Information", cat: "when",
    q: "When did all women get the right to vote?",
    a: ["1920", "After World War I", "(With the) 19th Amendment"] },
  { n: 103, sub: "Recent American History and Other Important Historical Information", cat: "describes",
    q: "What was the Great Depression?",
    a: ["Longest economic recession in modern history"] },
  { n: 104, sub: "Recent American History and Other Important Historical Information", cat: "when",
    q: "When did the Great Depression start?",
    a: ["The Great Crash (1929)", "Stock market crash of 1929"] },
  { n: 105, sub: "Recent American History and Other Important Historical Information", cat: "person",
    q: "Who was president during the Great Depression and World War II?",
    a: ["(Franklin) Roosevelt"] },
  { n: 106, sub: "Recent American History and Other Important Historical Information", cat: "reason",
    q: "Why did the United States enter World War II?",
    a: ["(Bombing of) Pearl Harbor", "Japanese attacked Pearl Harbor", "To support the Allied Powers (England, France, and Russia)", "To oppose the Axis Powers (Germany, Italy, and Japan)"] },
  { n: 107, sub: "Recent American History and Other Important Historical Information", cat: "famous",
    q: "Dwight Eisenhower is famous for many things. Name one.",
    a: ["General during World War II", "President at the end of (during) the Korean War", "34th president of the United States", "Signed the Federal-Aid Highway Act of 1956 (Created the Interstate System)"] },
  { n: 108, sub: "Recent American History and Other Important Historical Information", cat: "nation",
    q: "Who was the United States’ main rival during the Cold War?",
    a: ["Soviet Union", "USSR", "Russia"], r: true },
  { n: 109, sub: "Recent American History and Other Important Historical Information", cat: "concern",
    q: "During the Cold War, what was one main concern of the United States?",
    a: ["Communism", "Nuclear war"], r: true },
  { n: 110, sub: "Recent American History and Other Important Historical Information", cat: "reason",
    q: "Why did the United States enter the Korean War?",
    a: ["To stop the spread of communism"] },
  { n: 111, sub: "Recent American History and Other Important Historical Information", cat: "reason",
    q: "Why did the United States enter the Vietnam War?",
    a: ["To stop the spread of communism"] },
  { n: 112, sub: "Recent American History and Other Important Historical Information", cat: "describes",
    q: "What did the civil rights movement do?",
    a: ["Fought to end racial discrimination"] },
  { n: 113, sub: "Recent American History and Other Important Historical Information", cat: "famous",
    q: "Martin Luther King, Jr. is famous for many things. Name one.",
    a: ["Fought for civil rights", "Worked for equality for all Americans", "Worked to ensure that people would “not be judged by the color of their skin, but by the content of their character”"], star: true },
  { n: 114, sub: "Recent American History and Other Important Historical Information", cat: "reason",
    q: "Why did the United States enter the Persian Gulf War?",
    a: ["To force the Iraqi military from Kuwait"] },
  { n: 115, sub: "Recent American History and Other Important Historical Information", cat: "describes",
    q: "What major event happened on September 11, 2001 in the United States?",
    a: ["Terrorists attacked the United States", "Terrorists took over two planes and crashed them into the World Trade Center in New York City", "Terrorists took over a plane and crashed into the Pentagon in Arlington, Virginia", "Terrorists took over a plane originally aimed at Washington, D.C., and crashed in a field in Pennsylvania"], star: true },
  { n: 116, sub: "Recent American History and Other Important Historical Information", cat: "war",
    q: "Name one U.S. military conflict after the September 11, 2001 attacks.",
    a: ["(Global) War on Terror", "War in Afghanistan", "War in Iraq"] },
  { n: 117, sub: "Recent American History and Other Important Historical Information", cat: "tribe",
    q: "Name one American Indian tribe in the United States.",
    a: ["Apache", "Blackfeet", "Cayuga", "Cherokee", "Cheyenne", "Chippewa", "Choctaw", "Creek", "Crow", "Hopi", "Huron", "Inupiat", "Lakota", "Mohawk", "Mohegan", "Navajo", "Oneida", "Onondaga", "Pueblo", "Seminole", "Seneca", "Shawnee", "Sioux", "Teton", "Tuscarora For a complete list of tribes, please visit bia.gov."], r: true },
  { n: 118, sub: "Recent American History and Other Important Historical Information", cat: "innovation",
    q: "Name one example of an American innovation.",
    a: ["Light bulb", "Automobile (cars, internal combustion engine)", "Skyscrapers", "Airplane", "Assembly line", "Landing on the moon", "Integrated circuit (IC)"], r: true },
  { n: 119, sub: "Symbols", cat: "place",
    q: "What is the capital of the United States?",
    a: ["Washington, D.C."] },
  { n: 120, sub: "Symbols", cat: "place",
    q: "Where is the Statue of Liberty?",
    a: ["New York (Harbor)", "Liberty Island [Also acceptable are New Jersey, near New York City, and on the Hudson (River).]"], r: true },
  { n: 121, sub: "Symbols", cat: "reason",
    q: "Why does the flag have 13 stripes?",
    a: ["(Because there were) 13 original colonies", "(Because the stripes) represent the original colonies"], star: true },
  { n: 122, sub: "Symbols", cat: "reason",
    q: "Why does the flag have 50 stars?",
    a: ["(Because there is) one star for each state", "(Because) each star represents a state", "(Because there are) 50 states"] },
  { n: 123, sub: "Symbols", cat: "named",
    q: "What is the name of the national anthem?",
    a: ["The Star-Spangled Banner"], r: true },
  { n: 124, sub: "Symbols", cat: "meaning",
    q: "The Nation’s first motto was “E Pluribus Unum.” What does that mean?",
    a: ["Out of many, one", "We all become one"] },
  { n: 125, sub: "Holidays", cat: "describes",
    q: "What is Independence Day?",
    a: ["A holiday to celebrate U.S. independence (from Britain)", "The country’s birthday"] },
  { n: 126, sub: "Holidays", cat: "holiday", need: 3,
    q: "Name three national U.S. holidays.",
    a: ["New Year’s Day", "Martin Luther King, Jr. Day", "Presidents Day (Washington’s Birthday)", "Memorial Day", "Juneteenth", "Independence Day", "Labor Day", "Columbus Day", "Veterans Day", "Thanksgiving Day", "Christmas Day"], r: true, star: true },
  { n: 127, sub: "Holidays", cat: "describes",
    q: "What is Memorial Day?",
    a: ["A holiday to honor soldiers who died in military service"] },
  { n: 128, sub: "Holidays", cat: "describes",
    q: "What is Veterans Day?",
    a: ["A holiday to honor people in the (U.S.) military", "A holiday to honor people who have served (in the U.S. military)"] },
];
