/* GENERATED by tools/shelfgen.py from data/shelf.json — do not edit.
 *
 * The shelf: capability resources, sorted out of the pantry by one test —
 * does this teach a capability the reader keeps? What was left off, and
 * why, is recorded in data/shelf.json rather than lost, so the sorting
 * stays auditable and reversible.
 *
 * Those are SCOPE decisions about this project, not judgements about the
 * documents or their publisher. This shelf carries no policy asks, no
 * pledges and no campaign activity — from any source, including our own.
 *
 * `outline` is null wherever nobody has read the guide yet. It is never
 * inferred from a title: inventing the contents of somebody else's
 * document is exactly what the primary-source rule forbids, and a
 * plausible outline is worse than none because nobody checks it.
 *
 * Nothing here is hosted. These are their documents and we link to them.
 */

const SHELF_SOURCE = {
  name: "Ordinary People, Extraordinary Times",
  href: "https://ordinarypeopleaction.com/resources/",
};

const SHELF = [
  {
    "id": "fact-check",
    "action": "Take one claim you nearly shared, and check it before you do.",
    "blurb": "Where to check something before you pass it on.",
    "title": "How to Check Facts and Become “News Literate”",
    "where": "Action 02",
    "url": "https://ordinarypeopleaction.com/2026/08/24/how-to-check-facts-and-become-news-literate/",
    "button": "Action 02 · News Literacy Guide",
    "mode": "both",
    "capacity": "minutes",
    "reach": "solo",
    "disposition": [
      "dig",
      "learn"
    ],
    "outline": [
      "What today’s media environment does to a story — sensationalism, algorithms, consolidation",
      "Bias and literacy tools: AdFontes Media Bias Chart, AllSides, the News Literacy Project",
      "Fact-checking services: PolitiFact and FactCheck.org",
      "Who owns what, via the Future Media Project at Harvard",
      "Disinformation resources, and a list of independent and nonprofit newsrooms"
    ]
  },
  {
    "id": "media-literacy",
    "action": "Pick one post that made you angry this week, and work out why it was shown to you.",
    "blurb": "Where your news actually comes from, and what that changes.",
    "title": "Media Literacy Starter Kit",
    "where": "Action 02",
    "url": "https://ordinarypeopleaction.com/2026/08/24/media-literacy-starter-kit/",
    "button": "Action 02 · Media Literacy Kit",
    "mode": "understand",
    "capacity": "minutes",
    "reach": "solo",
    "disposition": [
      "learn",
      "dig"
    ],
    "outline": [
      "Local media — why community papers and public radio see things national outlets miss",
      "Public and independent media, and how each is funded",
      "Fact checking — FactCheck.org and PolitiFact",
      "Newsletters and new media — the newer shapes news arrives in"
    ]
  },
  {
    "id": "talk-to-children",
    "action": "Answer the question a kid in your life has already asked you.",
    "blurb": "For when someone small has been asking you things you did not have an answer for.",
    "title": "How to Talk With Children About What is Happening in the United States",
    "where": "Action 01",
    "url": "https://ordinarypeopleaction.com/2026/08/24/how-to-talk-with-children-about-what-is-happening-in-the-united-states/",
    "button": "Action 01 · Talking With Children",
    "mode": "do",
    "capacity": "minutes",
    "reach": "solo",
    "disposition": [
      "talk",
      "support"
    ],
    "outline": [
      "Multimedia and educational resources — PBS LearningMedia, KidCitizen",
      "Reading lists for children and teenagers",
      "How to talk about politics and the news, from mental-health and education groups",
      "Ways to get young people into civic life in their own community"
    ]
  },
  {
    "id": "discussion-guide",
    "action": "Ask four people to read one chapter, and set a date to talk about it.",
    "blurb": "Ready-made questions, so nobody has to invent them on the night.",
    "title": "Chapter 1 Discussion Guide",
    "where": "Action 01 (one per chapter, 01–07)",
    "url": "https://ordinarypeopleaction.com/2026/08/25/chapter-1-discussion-guide/",
    "button": "Action 01 · Chapter Discussion Guide",
    "mode": "both",
    "capacity": "hour",
    "reach": "group",
    "disposition": [
      "talk",
      "learn"
    ],
    "outline": [
      "What a democracy is made of, and the signs it is coming apart",
      "People-powered action — the “pick up a shovel” half",
      "Spectator mindset against agent mindset, side by side",
      "A reflection exercise turning a worry into something you could do",
      "Discussion questions for a group to work through together"
    ]
  },
  {
    "id": "civic-desert",
    "action": "Find out who actually covers local news where you live, and what nobody is covering.",
    "blurb": "For places with no local paper and no obvious way in.",
    "title": "How To Engage If You’re In A Civic Desert",
    "where": "Action 03",
    "url": "https://ordinarypeopleaction.com/2026/08/24/how-to-engage-if-youre-in-a-civic-desert/",
    "button": "Action 03 · Civic Desert Guide",
    "mode": "both",
    "capacity": "hour",
    "reach": "either",
    "disposition": [
      "dig",
      "showup"
    ],
    "outline": [
      "Use what is already there — the library as the community hub it already is",
      "Invest in your news ecosystem: public radio, local journalism",
      "Meet the people who actually decide things, at meetings that are already public",
      "Third spaces — holding something in the coffee shop rather than waiting for a venue",
      "National organisations that work in small places: AmeriCorps Seniors, Weave, Idealist, Mutual Aid Hub",
      "A list of concrete starting points, from nature clubs to serving as an election official"
    ]
  },
  {
    "id": "joy-pathways",
    "action": "Put one thing on this week’s calendar that has nothing to do with the news.",
    "blurb": "The people who keep going are not the ones who are angriest.",
    "title": "Pathways to Joy",
    "where": "Action 05",
    "url": "https://ordinarypeopleaction.com/2026/08/24/pathways-to-joy/",
    "button": "Action 05 · Pathways to Joy",
    "mode": "do",
    "capacity": "minutes",
    "reach": "solo",
    "disposition": [
      "support",
      "make"
    ],
    "outline": [
      "Daily routines — small practices that actually bring you joy",
      "Regular rituals, weekly or monthly, that you keep",
      "Gratitude, and how to make it a habit rather than a mood",
      "Embodiment — laughter, movement, eating like you noticed",
      "Community: film nights, volunteering, classes",
      "Mindfulness, and putting your attention where you meant to",
      "Sharing it — telling the story so somebody else starts"
    ]
  },
  {
    "id": "spectator-to-agent",
    "action": "Write down one thing you have been watching happen — and one thing you could do about it.",
    "blurb": "For the specific feeling of watching it all happen and not knowing where to stand.",
    "title": "Moving from a Spectator Mindset to an Agent Mindset through Civic Engagement",
    "where": "Action 01",
    "url": "https://ordinarypeopleaction.com/2026/08/24/moving-from-a-spectator-mindset-to-an-agent-mindset-through-civic-engagement/",
    "button": "Action 01 · Spectator to Agent",
    "mode": "understand",
    "capacity": "minutes",
    "reach": "solo",
    "disposition": [
      "learn",
      "support"
    ],
    "outline": [
      "Why inaction costs more than action — “courage is the new currency”",
      "A short essay framing the shift from watching to doing",
      "A curated list of ways in, for general civic engagement",
      "A second list aimed at young people and students"
    ]
  },
  {
    "id": "dinners",
    "action": "Invite five people to dinner and let their questions start it.",
    "blurb": "A format for having the conversation over a meal, with people you already eat with.",
    "title": "Dinners for Democracy",
    "where": "Act Today",
    "url": "https://democracyforward.org/dinnersfordemocracy/",
    "button": "Act Today · Dinners for Democracy",
    "mode": "do",
    "capacity": "hour",
    "reach": "group",
    "disposition": [
      "talk",
      "make"
    ],
    "outline": null
  },
  {
    "id": "courage-films",
    "action": "Watch one film about somebody who did it anyway.",
    "blurb": "For an evening when you do not have another chapter in you.",
    "title": "Movies About Courageous and Inspiring People",
    "where": "Action 05",
    "url": "https://ordinarypeopleaction.com/2026/08/25/movies-about-courageous-and-inspiring-people/",
    "button": "Action 05 · Films Worth Watching",
    "mode": "understand",
    "capacity": "hour",
    "reach": "either",
    "disposition": [
      "learn",
      "support"
    ],
    "outline": [
      "Films from 1976 to 2019, each with director, year and what it is about",
      "Civil rights and voting rights: Selma, and the march at Edmund Pettus Bridge",
      "Press and accountability: All the President’s Men",
      "People who were not supposed to be there: Hidden Figures",
      "Lives that changed something: King, Milk, Ginsburg, Robinson"
    ]
  },
  {
    "id": "keep-going",
    "action": "Decide now what you will do on the week you stop feeling like it.",
    "blurb": "For the second month, which is when most of this stops.",
    "title": "More Tools for the Journey Ahead",
    "where": "Action 07",
    "url": "https://ordinarypeopleaction.com/2026/08/24/more-tools-for-the-journey-ahead/",
    "button": "Action 07 · Tools for the Journey",
    "mode": "both",
    "capacity": "minutes",
    "reach": "solo",
    "disposition": [
      "support",
      "learn"
    ],
    "outline": [
      "Seven things to do when the first burst of energy has gone",
      "Start at your own front door rather than nationally",
      "Information sobriety — what you let in, and how often",
      "Nonviolent collective action, and what it asks of you",
      "Personal and community resilience for a long stretch"
    ]
  }
];

/* Counts for the shelf page, generated so they cannot drift from the data.
 * "considered" is everything we looked at in this collection. */
const SHELF_STATS = {
  "considered": 25,
  "carried": 10,
  "held": 5,
  "outOfScope": 10,
  "read": 14,
  "source": "Ordinary People, Extraordinary Times",
  "sourceHref": "https://ordinarypeopleaction.com/resources/"
};
